name: dose_certa
description: Aplicativo para ajudar pacientes a tomarem seus medicamentos corretamente.
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  hive_generator: 2.0.1
  hive_test: ^1.0.0
  path: ^1.9.0

flutter:
  uses-material-design: true
